// Preview harness for app/shared/dmail.js — SAMPLE DATA ONLY (fictional brokers), no network. Build:
//   npx esbuild previews/dispatcher-mail-preview.src.js --bundle --format=iife --outfile=previews/dispatcher-mail-preview.bundle.js
import { mountDispatcherMail } from '../app/shared/dmail.js';
const me = 'aziz@loadboot.com', now = Date.now(), ago = (min) => new Date(now - min * 60000).toISOString();
const P = (email, name) => ({ email, name });
let M = [
  { id: 'm1', thread: 't1', folder: 'inbox', from_name: 'Dana Whitfield', from_email: 'dana@northlinefreight.example', to: [P(me, 'Abdul Aziz')], subject: 'Rate con — Dallas TX → Atlanta GA, 53\' dry van, pick Tue', text: 'Hi Aziz,\n\nRate confirmation attached for load NL-48213. $2,350 all-in, 781 miles. Please have the carrier sign and return today so we can lock the 08:00 appointment.\n\nThanks,\nDana', html: '<p>Hi Aziz,</p><p>Rate confirmation attached for load <b>NL-48213</b>. <b>$2,350 all-in</b>, 781 miles. Please have the carrier sign and return today so we can lock the 08:00 appointment.</p><p>Thanks,<br>Dana Whitfield<br>Northline Freight (sample)</p>', attachments: [{ idx: 0, name: 'RateCon-NL-48213.pdf', type: 'application/pdf', size: 184320 }], seen: false, starred: true, date: ago(6) },
  { id: 'm2', thread: 't2', folder: 'inbox', from_name: 'Marcus Reed', from_email: 'marcus@bluepeaklogistics.example', to: [P(me, 'Abdul Aziz')], subject: 'Carrier packet needed before we can tender', text: 'Aziz — before I can tender the Memphis load I need the carrier packet: W-9, COI naming us as certificate holder, and authority letter. Can you send today?', html: null, attachments: [], seen: false, starred: false, date: ago(48) },
  { id: 'm3', thread: 't3', folder: 'inbox', from_name: 'Priya Nair', from_email: 'priya@harborbridge.example', to: [P(me, 'Abdul Aziz')], subject: 'Re: Reefer capacity next week — Chicago outbound', text: 'Thanks Aziz. We will have 3 reefer loads out of Chicago Mon–Wed. I will send lanes and targets tomorrow morning.', html: null, attachments: [], seen: true, starred: false, date: ago(190) },
  { id: 'm3a', thread: 't3', folder: 'sent', from_name: 'Abdul Aziz', from_email: me, to: [P('priya@harborbridge.example', 'Priya Nair')], subject: 'Reefer capacity next week — Chicago outbound', text: 'Hi Priya,\n\nWe have two 53\' reefers empty in Chicago from Monday. Do you have anything outbound to the Southeast?\n\nAziz', html: null, attachments: [], seen: true, starred: false, date: ago(260) },
  { id: 'm4', thread: 't4', folder: 'inbox', from_name: 'Tom Alvarez', from_email: 'tom@ironridgecarriers.example', to: [P(me, 'Abdul Aziz')], subject: 'POD for yesterday\'s Nashville drop', text: 'Signed POD attached. Driver was unloaded by 14:20. Let me know when the invoice goes out.', html: null, attachments: [{ idx: 0, name: 'POD-Nashville.jpg', type: 'image/jpeg', size: 912384 }], seen: true, starred: false, date: ago(1500) },
  { id: 'm5', thread: 't5', folder: 'inbox', from_name: 'Northline Freight Billing', from_email: 'billing@northlinefreight.example', to: [P(me, 'Abdul Aziz')], subject: 'Remittance advice — invoice 10447', text: 'Payment for invoice 10447 has been scheduled. Remittance details inside.', html: null, attachments: [], seen: true, starred: false, date: ago(4300) },
  { id: 'm6', thread: 't6', folder: 'sent', from_name: 'Abdul Aziz', from_email: me, to: [P('marcus@bluepeaklogistics.example', 'Marcus Reed')], subject: 'Available: 53\' dry van, Memphis, Thursday AM', text: 'Marcus — one dry van empty in Memphis Thursday 07:00. Looking for anything toward Texas.', html: null, attachments: [], seen: true, starred: false, date: ago(900) },
  { id: 'm7', thread: 'draft:m7', folder: 'drafts', from_name: 'Abdul Aziz', from_email: me, to: [P('dana@northlinefreight.example', 'Dana Whitfield')], subject: 'Signed rate con NL-48213', text: 'Hi Dana, signed rate con attached.', html: 'Hi Dana, signed rate con attached.', attachments: [], seen: true, starred: false, date: ago(3), draft_meta: { mode: 'new' } },
];
const delay = (v) => new Promise((r) => setTimeout(() => r(v), 180));
const counts = () => ({ inbox: new Set(M.filter((m) => m.folder === 'inbox' && !m.seen).map((m) => m.thread)).size, drafts: M.filter((m) => m.folder === 'drafts').length, spam: 0 });
const api = {
  dmailBootstrap: () => delay({ enabled: true, staff_view: false, can_delete: false, account: { id: 'acc', address: me, display_name: 'Abdul Aziz — LoadBoot Dispatch', signature_html: '<b>Abdul Aziz Shinwari</b><br>Dispatcher · LoadBoot<br><a href="https://loadboot.com">loadboot.com</a>', status: 'active', last_sync_at: ago(0.3), sync_problem: false }, counts: counts() }),
  dmailList: ({ folder, q }) => { let b = M.filter((m) => q ? (m.subject + m.text + m.from_name).toLowerCase().includes(q.toLowerCase()) : folder === 'starred' ? m.starred : m.folder === folder); const by = {}; b.forEach((m) => { (by[m.thread] = by[m.thread] || []).push(m); });
    const rows = Object.values(by).map((l) => { l.sort((a, c) => a.date < c.date ? 1 : -1); const x = l[0], all = M.filter((m) => m.thread === x.thread && m.folder !== 'drafts'); return { thread: x.thread, ids: l.map((m) => m.id), id: x.id, folder: x.folder, date: x.date, unread: l.some((m) => !m.seen), starred: l.some((m) => m.starred), has_attach: l.some((m) => m.attachments.length), subject: x.subject, snippet: x.text.replace(/\s+/g, ' ').slice(0, 160), from_name: x.from_name, from_email: x.from_email, to: x.to, total: all.length || 1, names: [...new Set(all.map((m) => m.from_email === me ? 'me' : m.from_name))] }; }).sort((a, c) => a.date < c.date ? 1 : -1);
    return delay({ rows, counts: counts(), last_sync_at: ago(0.3) }); },
  dmailThread: (a, t) => delay({ messages: M.filter((m) => m.thread === t).sort((a2, c) => a2.date > c.date ? 1 : -1).map((m) => Object.assign({ cc: [], bcc: [], snippet: m.text.slice(0, 120) }, m)) }),
  dmailDraftSave: (p) => delay({ ok: true, id: p.id || 'd' + Date.now() }), dmailDraftDiscard: (id) => { M = M.filter((m) => m.id !== id); return delay({ ok: true }); },
  dmailPoll: () => delay({ counts: counts(), latest: 'x', last_sync_at: ago(0.2), sync_problem: false }),
  dmailContacts: (a, q) => delay({ rows: M.filter((m) => m.from_email !== me && (m.from_email + m.from_name).toLowerCase().includes(q.toLowerCase())).map((m) => ({ email: m.from_email, name: m.from_name })).slice(0, 5) }),
  dmailAct: (b) => { const ids = new Set(b.ids || []); if (b.action === 'mark') M.forEach((m) => { if (ids.has(m.id)) { if ('seen' in b) m.seen = b.seen; if ('starred' in b) m.starred = b.starred; } }); if (b.action === 'move') M.forEach((m) => { if (ids.has(m.id)) m.folder = b.to; }); if (b.action === 'delete') M = M.filter((m) => !ids.has(m.id)); if (b.action === 'attachment') return delay(new Blob(['sample'])); return delay({ ok: true, added: 0 }); },
};
window.__dm = mountDispatcherMail(document.getElementById('host'), { api });
