-- bl_comm_0392: curated overlay. NOTE (22 Sep 2026): the variant recorded in staging's
-- supabase_migrations only inserted the keys and left the metadata to a hand-run statement.
-- This file is the reproducible form (full upsert) and is what production received.
-- bl_comm_0392: curated overlay. Every email LoadBoot sends, classified, grouped,
-- deduplicated and pointed at the screen it belongs to. Data only, no behaviour change.
alter table app_private.email_catalog drop constraint if exists email_catalog_status_check;
alter table app_private.email_catalog add constraint email_catalog_status_check
  check (status in ('live','legacy','retired','dead','test','planned','undocumented','dynamic'));

with v(key,name,purpose,class,audience_role,trigger_type,trigger_source,cadence,cap_note,preference_group,unsub_allowed,status,replaced_by,cc_deep_link) as (values
-- A. account and signup
('welcome.account','Welcome','First email after signup','T','carrier,broker,shipper','event','app_private.send_welcome_email','once per signup','once','account_critical',false,'live',null,'#/carriers'),
('welcome.agent','Welcome (agent)','First email after agent signup','T','agent','event','app_private.send_welcome_email','once per signup','once','account_critical',false,'live',null,'#/dispatchers'),
('welcome.broker','Welcome (broker)','First email after broker org created','T','broker','event','app_private.trg_partner_org_welcome','once','once','account_critical',false,'live',null,'#/partners'),
('welcome.shipper','Welcome (shipper)','First email after shipper org created','T','shipper','event','app_private.trg_partner_org_welcome','once','once','account_critical',false,'live',null,'#/partners'),
('welcome.founder_broker','Founder welcome','Hand-sent founder note to early brokers','P','broker','manual','hand-sent Aug 2026','ad-hoc',null,'marketing',true,'legacy',null,'#/partners'),
('welcome.application_received','Application received','Confirms carrier onboarding submission','T','carrier','event','public.cc_pocket_submit_onboarding','once per submission','once','account_critical',false,'live',null,'#/carriers'),
('account.created','Account created','Account creation notice','T','carrier,broker','event','signup path','once','once','account_critical',false,'legacy',null,'#/carriers'),
('account.violation','Violation issued','Tells the carrier a strike was issued and why','T','carrier','manual','public.cc_issue_violation','per violation',null,'account_critical',false,'live',null,'#/carriers'),
('account.closed','Account closed','Confirms account closure','T','carrier,broker','manual','public.cc_request_account_action','once','once','account_critical',false,'live',null,'#/settings'),
('account.request','Account action requested','Staff asked for an account action','T','carrier,broker','manual','public.cc_request_account_action','per request',null,'account_critical',false,'live',null,'#/carriers'),
('account.reopened','Account reopened','Account reinstated after closure','T','carrier,broker','manual','public.cc_reopen_account','once','once','account_critical',false,'live',null,'#/carriers'),
('account.pause','Account paused','Booking paused notice','T','carrier','manual','public.cc_pause_carrier','per pause',null,'account_critical',false,'live',null,'#/carriers'),
('account.resume','Account resumed','Booking resumed notice','T','carrier','manual','public.cc_pause_carrier','per resume',null,'account_critical',false,'live',null,'#/carriers'),
('account.deletion_requested','Deletion requested','Confirms a data deletion request','T','any','event','public.request_account_deletion','once','once','account_critical',false,'live',null,'#/settings'),
('agent.confirm_email','Confirm your email (agent)','Chases an unconfirmed agent email address','O','agent','cron','public.cc_run_onboarding_reminders','daily 14:00 UTC','UNKNOWN - verify','account_critical',false,'live',null,'#/dispatchers'),
('onboarding.confirm_email','Confirm your email','Chases an unconfirmed carrier email address','O','carrier','cron','public.cc_run_onboarding_reminders','daily 14:00 UTC','UNKNOWN - verify','account_critical',false,'live',null,'#/carrier-reminders'),
('carrier.reminder.confirm_email','Confirm your email (reminder engine)','Same chase from the reminder engine','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per cadence window','account_critical',false,'live',null,'#/carrier-reminders'),
-- B. onboarding and compliance
('onboarding.reminder','Finish onboarding','Chases an unfinished carrier onboarding','O','carrier','cron','public.cc_run_onboarding_reminders','daily 14:00 UTC','lifetime cap 3; resets on carrier activity','compliance',true,'live',null,'#/carriers'),
('agent.onboarding_reminder','Finish onboarding (agent)','Chases an unfinished agent onboarding','O','agent','cron','public.cc_run_onboarding_reminders','daily 14:00 UTC','UNKNOWN - verify','compliance',true,'live',null,'#/dispatchers'),
('onboarding.in_review','Application in review','Reassures while documents sit with compliance','T','carrier','cron','public.cc_run_onboarding_reminders','once per review cycle','once','compliance',false,'live',null,'#/carriers'),
('onboarding.decided','Onboarding decision','Approved or declined result','T','carrier','manual','public.cc_decide_onboarding','once per decision','once','account_critical',false,'live',null,'#/carriers'),
('onboarding.complete','Onboarding complete','All items cleared','T','carrier','event','public.cc_onboarding_review_item','once','once','compliance',false,'live',null,'#/documents'),
('onboarding.item_reject','Item needs changes','One onboarding item was rejected with the fix','T','carrier','manual','public.cc_onboarding_review_item','per item',null,'compliance',false,'live',null,'#/documents'),
('onboarding.item_reminder','Packet item reminder','Chases a missing packet item','O','broker,carrier','manual','public.cc_partner_packet_remind','staff click','human throttle','compliance',true,'live',null,'#/partner-intake'),
('onboarding.submitted','Onboarding submitted','Confirms the submission','T','carrier','event','public.cc_pocket_submit_onboarding','once','once','compliance',false,'live',null,'#/carriers'),
('ops.onboarding.submitted','New onboarding (staff)','Tells staff an onboarding landed','S','staff','event','public.cc_pocket_submit_onboarding','per submission',null,'staff_internal',false,'live',null,'#/carriers'),
('onboarding.guide','Onboarding guide','Hand-sent walkthrough','O','carrier','manual','hand-sent Aug 2026','ad-hoc',null,'compliance',true,'legacy',null,'#/carriers'),
('onboarding.status.update','Status update','Hand-sent status note','O','carrier','manual','hand-sent Aug 2026','ad-hoc',null,'compliance',true,'legacy',null,'#/carriers'),
('onboarding.finish_line','Almost done','Hand-sent final push','O','carrier','manual','hand-sent Aug 2026','ad-hoc',null,'compliance',true,'legacy',null,'#/carriers'),
('onboarding.mc_pending_ack','MC pending','Acknowledges a pending MC number','T','carrier','manual','hand-sent Aug 2026','ad-hoc',null,'compliance',false,'legacy',null,'#/carriers'),
('onboarding.broker_next_steps','Broker next steps','Hand-sent broker guidance','O','broker','manual','hand-sent Aug 2026','ad-hoc',null,'compliance',true,'legacy',null,'#/partners'),
('document.submitted','Document submitted (staff)','Tells staff a document arrived','S','staff','event','app_private.tg_document_submitted','per document',null,'staff_internal',false,'live',null,'#/documents'),
('document.uploaded','Document uploaded','Upload confirmation','T','carrier','event','upload trigger','per document',null,'compliance',false,'legacy',null,'#/documents'),
('document.reviewed.valid','Document approved','Tells the carrier one document passed','T','carrier','manual','app_private.compliance_decision_notify','one per item - four items send four emails',null,'compliance',false,'live',null,'#/documents'),
('document.reviewed.rejected','Document rejected','Tells the carrier what to fix','T','carrier','manual','app_private.compliance_decision_notify','one per item',null,'compliance',false,'live',null,'#/documents'),
('document.reviewed','Document reviewed (old)','Superseded by the .valid/.rejected pair','T','carrier','event','legacy path','-',null,'compliance',false,'retired','document.reviewed.valid','#/documents'),
('compliance.expiring','Document expiring','Warns before COI, authority, CDL or medical expires','O','carrier','cron','app_private.carrier_expiry_notify_run','every 2 hours','dedupe table + send window + daily cap','compliance',true,'live',null,'#/compliance'),
('compliance.complete','Compliance complete','All compliance items cleared','T','carrier','event','public.admin_review_document','once','once','compliance',false,'live',null,'#/compliance'),
('compliance.reminder','Compliance reminder','Hand-sent compliance chase','O','carrier','manual','hand-sent','ad-hoc',null,'compliance',true,'legacy',null,'#/compliance'),
('compliance.review.summary','Review summary','Neutral hand-written review summary','T','carrier','manual','app_private.sys_email direct','ad-hoc',null,'compliance',false,'live',null,'#/documents'),
('verification.result','Verification result','FMCSA verification outcome','T','carrier','event','verification path','per check',null,'compliance',false,'legacy',null,'#/compliance'),
('broker.verification','Broker verification','Broker authority verification outcome','T','broker','event','broker screening','per check',null,'compliance',false,'legacy',null,'#/broker-trust'),
('authority_lapsed','Authority lapsed','FMCSA authority no longer active','T','carrier','cron','app_private.fmcsa_authority_collect','every 5 min scan','edge triggered only - status change','account_critical',false,'live',null,'#/compliance'),
('packet_revalidation','Packet revalidation','Asks a broker to refresh packet items','O','broker','cron','app_private.cron_packet_revalidation','daily 07:30 UTC','unique per org+item+stage+cycle','compliance',true,'live',null,'#/partner-compliance'),
('packet_lapsed','Packet lapsed','Packet items went stale','O','broker','cron','app_private.cron_packet_revalidation','daily 07:30 UTC','one per cycle','compliance',true,'live',null,'#/partner-compliance'),
('packet.copy_request','Packet copy request','Asks the carrier for packet copies','T','carrier','manual','public.cc_request_packet_copies','staff click',null,'compliance',false,'live',null,'#/partners'),
('ops.packet.copy_request','Packet copy request (staff)','Staff copy of the request','S','staff','manual','public.cc_request_packet_copies','per request',null,'staff_internal',false,'live',null,'#/partners'),
('broker.identity_claim','Identity claim','Voice/email identity claim against the FMCSA record','T','broker','event','app_private.broker_identity_send_email','per claim',null,'account_critical',false,'live',null,'#/broker-trust'),
('broker.parent_confirm','Parent confirmation','Confirms the parent brokerage of a contact','T','broker','event','app_private.broker_parent_confirm_send_p','per claim',null,'account_critical',false,'live',null,'#/broker-trust'),
-- C. carrier activation reminders (pref-aware engine)
('carrier.reminder.docs_start','Start your documents','First nudge to upload documents','O','carrier','manual','app_private.reminder_dispatch','cadence gate, Send anyway override','one per cadence window','compliance',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.docs_fix','Fix your documents','Nudge after a rejection','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','compliance',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.docs_finish','Finish your documents','Nudge when documents are partly done','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','compliance',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.truck_add','Add your first truck','Nudge to register a truck','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.truck_continue','Finish adding trucks','Nudge to complete the fleet','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.driver_add','Add a driver','Nudge to add a driver','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.avail_start','Post your availability','Nudge to post daily truck availability','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.avail_confirm','Confirm availability','Asks to confirm today availability','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('carrier.reminder.avail_continue','Keep availability current','Nudge when availability went stale','O','carrier','manual','app_private.reminder_dispatch','cadence gate','one per window','load_ops',true,'live',null,'#/carrier-reminders'),
('fleet.first_truck_reminder','First truck reminder','Staff-clicked first truck chase','O','carrier','manual','public.cc_fleet_truck_remind','staff click','human throttle','load_ops',true,'live',null,'#/carriers'),
('carrier_weekly_summary','Weekly summary','Weekly account digest for the carrier','O','carrier','cron','app_private.carrier_weekly_digest_run','Mondays 13:00 UTC','one per week','digests',true,'live',null,'#/carriers'),
('announcement','Product announcement','Product news to an audience','P','carrier,broker,agent','event','app_private.tg_announcement_notify','per announcement',null,'product_announcements',true,'live',null,'#/announcements'),
-- D. loads, offers, trips
('offer.received','New offer','Sends a load offer to a carrier','T','carrier','manual','public.cc_offer_send','per offer','once per offer','load_ops',false,'live',null,'#/loads'),
('offer.expiring','Offer expiring','Warns before an offer lapses','T','carrier','cron','app_private.cron_offer_expiry_warnings','every 3 min','one shot per offer','load_ops',true,'live',null,'#/loads'),
('book.requested','Booking requested','Carrier asked to book a load','T','carrier','event','public.cc_request_book_load','per request','once','load_ops',false,'live',null,'#/booking-requests'),
('bookreq.received','Booking request received','Tells the broker a request came in','T','broker','event','app_private.trg_bookreq_broker_notify','per request','once','load_ops',false,'live',null,'#/booking-requests'),
('bookreq.sent','Booking request sent','Confirms the request to the carrier','T','carrier','event','app_private.trg_bookreq_carrier_confirm','per request','once','load_ops',false,'live',null,'#/booking-requests'),
('bookreq.expired','Booking request expired','Stale request swept','O','carrier','cron','public.cc_run_stale_bookreq_sweep','sweep','once','load_ops',true,'live',null,'#/booking-requests'),
('book.approved','Booking approved','Load is yours','T','carrier','manual','public.cc_decide_book_request','per decision','once','load_ops',false,'live',null,'#/booking-requests'),
('load.booked','Load booked','Tells the broker the load is covered','T','broker','event','app_private.trg_trips_broker_notify','per booking','once','load_ops',false,'live',null,'#/loads'),
('load.posted','Load posted','Broker load went live on the board','T','broker','manual','public.cc_decide_partner_load','per load','once','load_ops',false,'live',null,'#/loads'),
('trip.dispatched','Trip dispatched','Trip handed to the driver','T','broker','event','app_private.trg_trips_broker_notify','per trip','once','load_ops',false,'live',null,'#/trips'),
('trip.started','Trip started','Driver rolling','T','broker','event','app_private.trg_trips_broker_notify','per trip','once','load_ops',false,'live',null,'#/trips'),
('load.delivered','Load delivered','Delivery confirmation','T','broker','event','app_private.trg_trip_status_propagate','per trip','once','load_ops',false,'live',null,'#/trips'),
('load.pickup_late','Pickup at risk (broker)','Warns the broker a pickup is slipping','T','broker','cron','app_private.cron_pickup_watch','every 15 min','fires on risk transition only','load_ops',false,'live',null,'#/trips'),
('trip.pickup_late','Pickup at risk (carrier)','Warns the carrier a pickup is slipping','T','carrier','cron','app_private.cron_pickup_watch','every 15 min','transition only','load_ops',false,'live',null,'#/trips'),
('load.expired','Update your pickup date','Chases a broker whose load went stale','O','broker','cron','app_private.cron_expired_load_nag','hourly at :20','cap 4, demo skipped, ignores >30 days','load_ops',true,'live',null,'#/loads'),
('load.expired.ask','Reschedule request','Staff asks the broker to reschedule','T','broker','manual','public.cc_ask_reschedule','staff click',null,'load_ops',false,'live',null,'#/loads'),
('load.cancelled_by_broker','Load cancelled','Broker cancelled the load','T','carrier','manual','public.cc_partner_cancel_load','per cancellation','once','load_ops',false,'live',null,'#/loads'),
('load.cancelled_carrier_fault','Load cancelled (carrier fault)','Cancellation recorded against the carrier','T','carrier,broker','manual','public.cc_partner_cancel_load','per cancellation','once','load_ops',false,'live',null,'#/loads'),
('checklist.received','Checklist received','Confirms the trip checklist','T','carrier','event','app_private.trg_checklist_notify_carrier','per checklist','once','load_ops',false,'live',null,'#/trips'),
('checklist.cc_review','Checklist to review (staff)','Tells staff a checklist needs review','S','staff','event','app_private.trg_checklist_notify_cc','per checklist',null,'staff_internal',false,'live',null,'#/trips'),
('checklist.nag','Checklist reminder','Chases a missing trip checklist','O','broker','cron','app_private.cron_broker_checklist_nag','every 2h in transit, daily once delivered','cap 8, demo skipped','load_ops',true,'live',null,'#/trips'),
('trip.emergency','Trip emergency','Emergency raised on a trip','T','carrier,broker','event','public.cc_trip_emergency_request','per event','once','account_critical',false,'live',null,'#/trips'),
('safety.reschedule.broker','Safety reschedule','Incident reschedule agreed with the broker','T','broker','manual','public.cc_approve_incident_reschedule','per incident','once','load_ops',false,'live',null,'#/safety-desk'),
('rating.invite','Rate this trip','Asks both sides to rate a completed trip','P','carrier,broker','event','app_private.trg_trip_rating_invite','per completed trip','once per trip','digests',true,'planned',null,'#/trips'),
('load_email_dispatcher_received','Broker email received','Inbound broker load email routed to a dispatcher','T','dispatcher','inbound','app_private.lb_email_notify','per inbound email',null,'load_ops',false,'live',null,'#/email-loads'),
('load_email_needsinfo','Load needs info','Asks the broker for missing load details','T','broker','inbound','app_private.lb_email_notify','per email',null,'load_ops',false,'live',null,'#/email-loads'),
('load_email_claim','Load claim','Claim reply on an inbound load email','T','broker','inbound','app_private.lb_email_notify','per email',null,'load_ops',false,'live',null,'#/email-loads'),
('load_email_live','Load live','Inbound load went live','T','broker','inbound','app_private.lb_email_notify','per email',null,'load_ops',false,'live',null,'#/email-loads'),
-- E. money
('fee.invoice_due','Invoice due','Auto invoice raised on delivery','T','carrier,broker','event','app_private.auto_invoice_on_delivery','per invoice','once','billing',false,'live',null,'#/finance'),
('fee.invoice_paid','Invoice paid','Payment received receipt','T','carrier,broker','event','finance path','per payment','once','billing',false,'live',null,'#/finance'),
('invoice.reminder','Invoice reminder','Staff-clicked invoice chase','O','broker','manual','public.cc_invoice_send_reminder','staff click','human throttle','billing',true,'live',null,'#/finance'),
('pay.reminder','Payment reminder','Staff-clicked payment chase','O','broker,carrier','manual','public.pay_request_reminder','staff click','human throttle','billing',true,'live',null,'#/finance'),
('pay.confirm_nag','Confirm the payment','Chases an unconfirmed transfer','O','carrier','cron','app_private.pay_confirm_nag','every 12 hours','cap 7, demo skipped','billing',true,'live',null,'#/finance'),
('pay.confirmed','Payment confirmed','Confirms money received','T','carrier,broker','event','public.pay_confirm_received','per payment','once','billing',false,'live',null,'#/finance'),
('factoring.decision','Factoring decision','Factoring verification outcome','T','carrier','manual','public.cc_factoring_verify','per decision','once','billing',false,'live',null,'#/finance'),
('factoring.broker_notice','Factoring notice (broker)','NOA notice to the broker','T','broker','event','public.carrier_factoring_set','per change','once','billing',false,'live',null,'#/finance'),
('factoring.mode_change','Factoring mode changed','Factoring arrangement changed','T','carrier,broker','event','public.carrier_factoring_broker_set','per change','once','billing',false,'live',null,'#/finance'),
('factoring.booking_notice','NOA booking notice','Notice of assignment on a booking','T','broker','event','app_private.trg_trip_noa_notice','per trip','once','billing',false,'live',null,'#/finance'),
('agent.commission','Commission earned','Tells an agent a commission accrued','T','agent','event','app_private.trg_agent_on_commission','per accrual',null,'billing',false,'live',null,'#/referrals'),
('agent.payout_requested_self','Payout requested','Confirms the payout request to the agent','T','agent','event','public.agent_request_payout','per request','once','billing',false,'live',null,'#/referrals'),
('agent.payout_details_requested','Payout details needed','Finance needs payout details','T','agent','manual','public.cc_agent_payout_request_details','per request',null,'billing',false,'live',null,'#/referrals'),
('agent.payout_review','Payout under review','Payout verification result','T','agent','manual','public.cc_agent_payout_verify','per review',null,'billing',false,'live',null,'#/referrals'),
('health.adjustment','Health score adjusted','Explains a health score change','T','carrier','manual','public.cc_health_adjust','per adjustment','once','account_critical',false,'live',null,'#/carriers'),
('health.reset','Points restored','Health score points restored','T','carrier','manual','public.cc_health_reset_factor','per reset','once','account_critical',false,'live',null,'#/carriers'),
('health.poa_required','Plan of action required','Asks the carrier for a plan of action','T','carrier','manual','public.cc_request_poa','per request','once','account_critical',false,'live',null,'#/carriers')
)
insert into app_private.email_catalog as c
 (key,name,purpose,class,audience_role,trigger_type,trigger_source,cadence,cap_note,
  preference_group,unsub_allowed,status,replaced_by,cc_deep_link)
select v.key,v.name,v.purpose,v.class,v.audience_role,v.trigger_type,v.trigger_source,v.cadence,v.cap_note,
       v.preference_group,v.unsub_allowed,v.status,v.replaced_by,v.cc_deep_link
from v
on conflict (key) do update set
  name=excluded.name, purpose=excluded.purpose, class=excluded.class, audience_role=excluded.audience_role,
  trigger_type=excluded.trigger_type, trigger_source=excluded.trigger_source, cadence=excluded.cadence,
  cap_note=excluded.cap_note, preference_group=excluded.preference_group, unsub_allowed=excluded.unsub_allowed,
  status=excluded.status, replaced_by=excluded.replaced_by, cc_deep_link=excluded.cc_deep_link, updated_at=now();
