-- bl_cc_0138 — factoring verify also sets factoring_noa=true so pay_instructions routes
-- broker payments to the factor remit-to. Applied to STAGING + PROD via MCP.
-- See cc_factoring_verify in DB for the full body.
