-- bl_cc_0102 — CC manual onboarding reminders + visibility (hybrid with the auto engine).
-- cc_onboarding_remind(org, doc?) — per-document OR all-missing premium email (branded header,
--   missing list, CTA, help footer) + in-app to the carrier owner; 6h cooldown per target.
-- cc_onboarding_reminder_status(org) — last manual / last auto timestamps for the CC card.
-- UI: carrier360 Onboarding & compliance card — ✉ Remind per non-valid document row +
--   "✉ Send onboarding reminder (all missing)" + status line. Auto engine untouched.
-- Applied to staging 2026-07-15. Copy fn defs from staging for PROD + grants (authenticated only).

-- v2 (staging + PROD 2026-07-15): fixed after first real Gmail delivery test —
--   · double header removed (sys_email already wraps in the branded LoadBoot template; body now
--     starts at the h2 like every other system email)
--   · missing list is now REAL: every mandatory active compliance requirement WITHOUT a 'valid'
--     row for the org (new carriers with zero rows get the full mandatory list, not a placeholder)
--   · items render as MISSING-chip rows in a card table; subject counts items
--     ("N documents between you and your first load"); 💡 Pro tips box added.
