-- bl_int_0106 — REAL integrations (staging + PROD 2026-07-15). No vaporware:
-- 1) ELD/TELEMATICS LIVE INGEST — eld_integrations + ingest_token/last_ping_at;
--    carrier_eld_setup(provider, rotate) → per-carrier webhook token + POST instructions;
--    eld_ingest(token, lat, lng, speed?, at?) [granted to anon — token IS the auth]:
--    validates token+coords, routes position to the carrier's ACTIVE trip (trip_locations +
--    trips.last_* , tracking_method 'eld'). Any device that can POST = live integration.
--    NOTE: webhook URL string embeds the project ref — staging/prod versions differ by ref only.
-- 2) carrier_accounting_export(from,to) — invoices (gross/fee/net/lane/paid), expenses, confirmed
--    payments as JSON → portal downloads QuickBooks-compatible CSVs (Finance → Taxes).
-- 3) carrier_fuel_import(rows[]) — EFS/Comdata/WEX statement rows (parsed client-side) → fuel
--    expenses, max 500/import (Finance → Costs).
-- 4) carrier_fleet_optimization(days) — per-truck trips/miles/revenue/$mi/active-days + top-5
--    lanes from delivered trips (Fleet tab card).
-- UI: carrier Fleet (📈 optimization + 🛰 ELD cards), Finance Taxes (export), Costs (fuel import).
-- integrations.html: these moved to "Live today" with accurate labels; native OAuth/provider APIs
-- remain on the honest roadmap. Copy fn defs from staging/prod pg_get_functiondef as needed.

-- bl_int_0107 (staging + PROD 2026-07-15): ELD PROVIDER POLLING — direct Samsara/Motive connection
-- using the CARRIER'S OWN api token (no partnership needed):
--   · eld_integrations.api_token; carrier_eld_setup(provider, rotate, api_token) 3-arg (2-arg dropped)
--   · eld_poll_targets() — service-role-only list of active integrations w/ tokens + active trips
--   · edge function 'eld-poll' (both projects): polls Samsara (Bearer) / Motive (X-Api-Key) latest
--     vehicle location → feeds public.eld_ingest via the integration's ingest token; 3-min throttle
--   · cron 'lb-eld-poll' (*/5) via pg_net http_post with the project anon key (verify_jwt)
-- UI: Fleet → ELD card gains provider select + API-token Connect (Samsara/Motive instructions).
-- STILL contract-blocked: QuickBooks OAuth two-way (needs owner's Intuit app keys — will build on
-- request), fuel-card provider APIs (WEX/Comdata partnerships), multi-fleet enterprise (deferred).
