-- bl_out_0235_outreach_templates — full template refresh.
-- Broker series rewritten: every email = one real broker problem -> tips they can use
-- TODAY without us -> how LoadBoot automates it -> free-to-join CTA. Carrier series
-- personalized ({STATE}, live {RATE_*}) + an explicit signup CTA + Spanish PS on d1.
-- Every CTA link carries utm + &oc={OC} (per-contact click attribution, bl_out_0234).
-- Every footer now carries the CAN-SPAM postal address.

-- =============================================== BROKER ===============================================

update app_private.outreach_templates set parts=null,
subject='your loads, covered by FMCSA-verified carriers — free',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Hi,</p><p>I run LoadBoot, a free load board where every carrier is FMCSA-verified before they can bid &mdash; authority, insurance, even the truck's VIN matched against its insurance certificate. I found {NAME} on the broker register.</p><p>Two ways to try it &mdash; pick the lazier one:</p><p><b>Zero effort:</b> add <b>loads@loadboot.com</b> to the load list you already email your carriers. Your loads land on our board automatically &mdash; free, no per-post fee, and your contact info stays on every load. Nothing about how you work changes.</p><p><b>Two minutes:</b> <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d1&oc={OC}" style="color:#0883F7">create a free broker account</a> and post directly &mdash; post, cover, rate con and invoice, one screen.</p><p>Reply with any question &mdash; a real person answers, not a sales queue.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d1&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=1;

update app_private.outreach_templates set parts=null,
subject='the 5-minute check that stops double-brokering',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Freight fraud is the worst it has ever been, and most of it walks in through a rushed carrier setup. Five checks, five minutes, before you tender to anyone new:</p><p>1. Call the phone number on the carrier's <b>FMCSA record</b> &mdash; not the one in their email signature.<br>2. Get the COI from the insurance <b>agent</b> directly, then call the agent back on the agency's public number.<br>3. Match the truck's <b>VIN</b> to the scheduled autos on that COI.<br>4. Authority under 6 months + a brand-new factoring NOA + pressure to move today = slow down.<br>5. If the dispatcher &ldquo;can't do a quick call&rdquo; about pickup details &mdash; walk.</p><p>On LoadBoot every one of those runs <b>automatically at booking</b> &mdash; a carrier that fails cannot bid on your load. <a href="https://loadboot.com/compliance.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d2&oc={OC}" style="color:#0883F7">Here is how the verification works</a> &mdash; and <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d2&oc={OC}" style="color:#0883F7">posting is free, permanently</a>.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d2&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=2;

update app_private.outreach_templates set parts=null,
subject='"where''s my truck" should be a dead question',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Every check call is a minute nobody gets back &mdash; times every load, every day.</p><p>Two things you can do this week, with or without us: write <b>arrive/depart timestamps into your rate con as a requirement</b>, and give your shipper <b>one tracking link</b> instead of a phone chain.</p><p>On LoadBoot each load carries live GPS with geofenced arrive/depart stamps &mdash; your shipper's &ldquo;where is my freight&rdquo; answers itself, and detention arguments end with a shared clock instead of two phone stories.</p><p><a href="https://loadboot.com/gps-tracking.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d3&oc={OC}" style="color:#0883F7">See how the tracking works</a> &middot; <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d3&oc={OC}" style="color:#0883F7">post loads free</a>.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d3&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=3;

update app_private.outreach_templates set parts=null,
subject='pay the real detention claims, kill the fake ones',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Detention is only hard because both sides are guessing. Three lines to put in your next rate con: the <b>free time</b> (two hours is standard), the <b>$/hr after it</b>, and <b>which clock decides</b>. Then pay clean claims inside 48 hours &mdash; carriers remember who pays, and your hardest lanes get covered first.</p><p>With geofenced timestamps you pay the real claims fast and decline the fake ones with proof instead of a fight. <a href="https://loadboot.com/detention-pay-policy.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d4&oc={OC}" style="color:#0883F7">Here is the policy we use</a> &mdash; steal it even if you never use us.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d4&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=4;

update app_private.outreach_templates set parts=null,
subject='5:40pm Friday, freight on the dock',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Vetting is easy on Monday morning. It fails at 5:40pm on a Friday with freight on the dock and one truck available.</p><p>The playbook that saves that hour: <b>post early</b> with honest appointment windows; keep a <b>bench of five small carriers per lane</b> who answer their own phones; and when 12 pallets won't fill a 53', <b>price it as a partial</b> instead of paying for air.</p><p>On LoadBoot the vetting runs at booking, automatically &mdash; authority, insurance, safety record, VIN-to-COI. Your worst day gets vetted exactly like your best. <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d5&oc={OC}" style="color:#0883F7">Post your next load free</a>.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d5&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=5;

update app_private.outreach_templates set parts=null,
subject='one screen: post, cover, rate con, invoice',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Most brokerages run one system to post, another to track, a third for rate cons and a fourth for invoices &mdash; and re-key the same load into each. Time one load end-to-end this week: fifteen minutes of re-typing per load is normal, and it is pure margin.</p><p>LoadBoot does all four on one screen: post, cover with a verified carrier, send the rate con, settle. <a href="https://loadboot.com/payments-settlements.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d6&oc={OC}" style="color:#0883F7">Here is how the money side works</a> &middot; <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d6&oc={OC}" style="color:#0883F7">free to post, always</a>.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d6&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=6;

update app_private.outreach_templates set parts=null,
subject='last one from me',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>My last email &mdash; no more after this.</p><p>The short version: posting on LoadBoot is free forever, every carrier arrives FMCSA-verified with the truck's VIN matched to its insurance, and every load carries GPS proof. <a href="https://loadboot.com/create-broker-account.html?utm_source=email&utm_medium=outreach&utm_campaign=broker-d7&oc={OC}" style="color:#0883F7">Two minutes to a free account</a> &mdash; or skip all of it and add <b>loads@loadboot.com</b> to your daily load blast; your freight reaches our carriers with zero change to how you work.</p><p>If none of that is useful, no hard feelings. The number below reaches me any hour if that ever changes.</p><p style="margin:24px 0 0">Riley<br>Broker Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=broker-d7&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='broker' and day=7;

-- =============================================== CARRIER ===============================================

update app_private.outreach_templates set parts=null,
subject='what {STATE} lanes are paying this week',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Hi,</p><p>I run LoadBoot, a load board and dispatch platform. I found {NAME} on the FMCSA register, so forgive the cold email.</p><p>This week's all-in spot averages: dry van <b>${RATE_VAN}/mi</b>, reefer <b>${RATE_REEFER}/mi</b>, flatbed <b>${RATE_FLATBED}/mi</b>. <a href="https://loadboot.com/market-rates.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d1&oc={OC}" style="color:#0883F7">Your lanes are here</a> &mdash; free, no login.</p><p>One offer, no signup: <b>reply with your equipment and the two or three lanes you actually run</b>, and I will send you what those lanes are paying right now, plus matching loads as they come in. That is the whole pitch.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d1&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:13px;color:#64748b;margin-top:10px">PD: &iquest;Prefieres espa&ntilde;ol? Responde en espa&ntilde;ol &mdash; contestamos igual.</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=1;

update app_private.outreach_templates set parts=null,
subject='why detention money goes unpaid',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Brokers pay detention all the time. They just do not pay carriers who ask three days late with no times.</p><p>What gets paid: in/out times recorded at the gate, one timestamped photo, and the invoice sent the same day. That is nearly the whole trick.</p><p>The full playbook: <a href="https://loadboot.com/detention-pay-policy.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d2&oc={OC}" style="color:#0883F7">how to actually collect detention</a>.</p><p>And if a broker owes you detention right now, reply with what happened. I will tell you straight whether it is collectable.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d2&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=2;

update app_private.outreach_templates set parts=null,
subject='three lines in a rate con worth reading twice',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Almost every rate con has three lines that quietly move money from you to the broker: the free-time clause, the &ldquo;all-in&rdquo; wording, and whether pay terms start at POD <i>received</i> or POD <i>approved</i>.</p><p>I broke a real one down line by line: <a href="https://loadboot.com/how-to-read-a-rate-confirmation.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d3&oc={OC}" style="color:#0883F7">how to read a rate confirmation</a>.</p><p>Want a second pair of eyes on one of yours? Reply and attach it. Free, and I answer these myself.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d3&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=3;

update app_private.outreach_templates set parts=null,
subject='do you know your real cost per mile?',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Most owner-operators who tell me a load &ldquo;made money&rdquo; are guessing. Truck payment, insurance, maintenance, tires, permits, your own pay &mdash; the real number is usually higher than it feels.</p><p>I built a free calculator. Two minutes, no email, no signup: <a href="https://loadboot.com/cost-per-mile-calculator.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d4&oc={OC}" style="color:#0883F7">work out your cost per mile</a>.</p><p>Once you know your number, &ldquo;that's the market rate&rdquo; stops working on you.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d4&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=4;

update app_private.outreach_templates set parts=null,
subject='new authority? the first 90 days decide everything',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>If {NAME} is a newer authority: the first 90 days end more trucking companies than the next five years, and it is almost never the driving. It is the filings and the cash flow.</p><p>BOC-3, UCR, 2290, insurance actually showing on your FMCSA record, a factoring NOA to every broker &mdash; in the right order. I wrote it up: <a href="https://loadboot.com/how-to-get-loads-with-new-authority.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d5&oc={OC}" style="color:#0883F7">the first 90 days, step by step</a>.</p><p>And when you are ready for loads: <a href="https://loadboot.com/create-carrier-account.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d5&oc={OC}" style="color:#0883F7">a free LoadBoot account</a> gets your COI read by AI in minutes, your authority monitored, and lane matches sent to your inbox &mdash; so brokers see you verified before they ever call.</p><p>Stuck on any of it? Reply &mdash; a real person answers, usually within the hour.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d5&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=5;

update app_private.outreach_templates set parts=null,
subject='waiting 30 days for money you already earned',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Net-30 is how small carriers die with full order books. The load is delivered, the fuel is paid, and the money arrives next month.</p><p>If you factor, do it right &mdash; the NOA has to reach every broker you haul for, or the check goes to the wrong party and becomes your problem. Plain-English guide: <a href="https://loadboot.com/factoring-noa.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d6&oc={OC}" style="color:#0883F7">factoring and the NOA, done right</a>.</p><p>On LoadBoot, invoices and settlements live with the load, so nothing waits because paperwork got lost.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d6&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=6;

update app_private.outreach_templates set parts=null,
subject='last one from me',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>This is my last email &mdash; I do not chase people forever.</p><p>The short version: LoadBoot is a free load board with FMCSA-verified companies on both sides, live market rates, GPS tracking and invoicing in one place &mdash; run by people who answer their own phone, any hour. <a href="https://loadboot.com/create-carrier-account.html?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d7&oc={OC}" style="color:#0883F7">An account takes two minutes</a> &mdash; or just reply with your lanes and I will email you matches myself.</p><p>Good luck out there. It is a hard business, run by tough people.</p><p style="margin:24px 0 0">Riley<br>Carrier Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=carrier-d7&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='carrier' and day=7;

-- =============================================== SHIPPER ===============================================

update app_private.outreach_templates set parts=null,
subject='a freight-protection checklist for shippers',
html=$T$<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.7;color:#1a1a1a;max-width:560px"><p>Hi,</p><p>I run LoadBoot, a direct-to-carrier shipping platform. I found {NAME} in the shipper register.</p><p>Whether or not you ever use us: we wrote a plain-English checklist on protecting freight from loss, damage and double-brokering fraud &mdash; checks that take minutes and regularly save five figures. <a href="https://loadboot.com/protect-freight-from-loss-damage-and-fraud.html?utm_source=email&utm_medium=outreach&utm_campaign=shipper-d1&oc={OC}" style="color:#0883F7">The checklist is here</a>, free, no signup.</p><p>And if you ever want lanes quoted direct to verified carriers with live GPS on every load, just reply &mdash; we read every message that lands here.</p><p style="margin:24px 0 0">Riley<br>Shipper Support, LoadBoot<br><a href="https://loadboot.com?utm_source=email&utm_medium=outreach&utm_campaign=shipper-d1&oc={OC}" style="color:#0883F7">loadboot.com</a> &middot; +1 (469) 253-7575, any hour</p><p style="font-size:12px;color:#8a8a8a;margin-top:28px;border-top:1px solid #eeeeee;padding-top:12px">I found {NAME} on the public FMCSA register. If you would rather not hear from me, <a href="{UNSUB}" style="color:#8a8a8a">one click here</a> and I stop.<br>LoadBoot LLC &middot; 30 N Gould St Ste N, Sheridan, WY 82801</p></div>$T$
where audience='shipper' and day=1;
