// us-cities.js — offline 'City, ST' suggestion list for address/home-base inputs.
// No external API: fast, free, works on mobile. ~342 major US freight cities.
export const US_CITIES = [
  'Aberdeen, SD',
  'Abilene, TX',
  'Akron, OH',
  'Albany, GA',
  'Albany, NY',
  'Albuquerque, NM',
  'Alexandria, LA',
  'Allentown, PA',
  'Amarillo, TX',
  'Anchorage, AK',
  'Ann Arbor, MI',
  'Annapolis, MD',
  'Appleton, WI',
  'Ardmore, OK',
  'Arlington, TX',
  'Asheville, NC',
  'Atlanta, GA',
  'Augusta, GA',
  'Augusta, ME',
  'Aurora, CO',
  'Aurora, IL',
  'Austin, TX',
  'Bakersfield, CA',
  'Baltimore, MD',
  'Bangor, ME',
  'Barstow, CA',
  'Baton Rouge, LA',
  'Battle Creek, MI',
  'Beaumont, TX',
  'Bend, OR',
  'Billings, MT',
  'Binghamton, NY',
  'Birmingham, AL',
  'Bismarck, ND',
  'Bloomington, IL',
  'Boise, ID',
  'Bolingbrook, IL',
  'Boston, MA',
  'Bowling Green, KY',
  'Bozeman, MT',
  'Bridgeport, CT',
  'Brownsville, TX',
  'Buffalo, NY',
  'Burlington, VT',
  'Butte, MT',
  'Camden, NJ',
  'Canton, OH',
  'Carlisle, PA',
  'Carson City, NV',
  'Casper, WY',
  'Cedar Rapids, IA',
  'Champaign, IL',
  'Charleston, SC',
  'Charleston, WV',
  'Charlotte, NC',
  'Chattanooga, TN',
  'Chesapeake, VA',
  'Cheyenne, WY',
  'Chicago, IL',
  'Cincinnati, OH',
  'Clarksville, TN',
  'Cleveland, OH',
  'Clovis, NM',
  'Colorado Springs, CO',
  'Columbia, MO',
  'Columbia, SC',
  'Columbus, GA',
  'Columbus, OH',
  'Commerce City, CO',
  'Concord, NH',
  'Corpus Christi, TX',
  'Council Bluffs, IA',
  'Dallas, TX',
  'Dalton, GA',
  'Danville, VA',
  'Davenport, IA',
  'Dayton, OH',
  'Daytona Beach, FL',
  'Decatur, IL',
  'Del Rio, TX',
  'Denver, CO',
  'Des Moines, IA',
  'Detroit, MI',
  'Dodge City, KS',
  'Dothan, AL',
  'Dover, DE',
  'Duluth, MN',
  'Durham, NC',
  'Eagle Pass, TX',
  'East St. Louis, IL',
  'Eau Claire, WI',
  'Edison, NJ',
  'El Paso, TX',
  'Elgin, IL',
  'Elizabeth, NJ',
  'Elizabethtown, KY',
  'Elkhart, IN',
  'Elko, NV',
  'Enid, OK',
  'Erie, PA',
  'Eugene, OR',
  'Evansville, IN',
  'Everett, WA',
  'Fairbanks, AK',
  'Fargo, ND',
  'Fayetteville, AR',
  'Fayetteville, NC',
  'Flagstaff, AZ',
  'Flint, MI',
  'Florence, SC',
  'Fontana, CA',
  'Fort Collins, CO',
  'Fort Lauderdale, FL',
  'Fort Myers, FL',
  'Fort Smith, AR',
  'Fort Wayne, IN',
  'Fort Worth, TX',
  'Frederick, MD',
  'Fresno, CA',
  'Gainesville, GA',
  'Gallup, NM',
  'Garden City, KS',
  'Garland, TX',
  'Gary, IN',
  'Gillette, WY',
  'Glendale, AZ',
  'Grand Forks, ND',
  'Grand Island, NE',
  'Grand Junction, CO',
  'Grand Rapids, MI',
  'Great Falls, MT',
  'Green Bay, WI',
  'Greensboro, NC',
  'Greenville, MS',
  'Greenville, SC',
  'Gulfport, MS',
  'Hagerstown, MD',
  'Harrisburg, PA',
  'Hartford, CT',
  'Hattiesburg, MS',
  'Honolulu, HI',
  'Houston, TX',
  'Huntington, WV',
  'Huntsville, AL',
  'Idaho Falls, ID',
  'Indianapolis, IN',
  'Irving, TX',
  'Jackson, MS',
  'Jackson, TN',
  'Jacksonville, FL',
  'Jersey City, NJ',
  'Joliet, IL',
  'Jonesboro, AR',
  'Joplin, MO',
  'Juneau, AK',
  'Kalamazoo, MI',
  'Kansas City, KS',
  'Kansas City, MO',
  'Kearney, NE',
  'Kenosha, WI',
  'Kent, WA',
  'Knoxville, TN',
  'La Crosse, WI',
  'Lafayette, IN',
  'Lafayette, LA',
  'Lake Charles, LA',
  'Lakeland, FL',
  'Lancaster, PA',
  'Lansing, MI',
  'Laramie, WY',
  'Laredo, TX',
  'Las Cruces, NM',
  'Las Vegas, NV',
  'Lawton, OK',
  'Lexington, KY',
  'Lima, OH',
  'Lincoln, NE',
  'Little Rock, AR',
  'Long Beach, CA',
  'Los Angeles, CA',
  'Louisville, KY',
  'Lowell, MA',
  'Lubbock, TX',
  'Lynchburg, VA',
  'Macon, GA',
  'Madison, WI',
  'Manchester, NH',
  'Mankato, MN',
  'McAllen, TX',
  'Medford, OR',
  'Memphis, TN',
  'Meridian, MS',
  'Mesa, AZ',
  'Miami, FL',
  'Midland, TX',
  'Milwaukee, WI',
  'Minneapolis, MN',
  'Minot, ND',
  'Missoula, MT',
  'Mobile, AL',
  'Modesto, CA',
  'Monroe, LA',
  'Montgomery, AL',
  'Montpelier, VT',
  'Morgantown, WV',
  'Murfreesboro, TN',
  'Muskogee, OK',
  'Nampa, ID',
  'Nashua, NH',
  'Nashville, TN',
  'New Bedford, MA',
  'New Haven, CT',
  'New Orleans, LA',
  'New York, NY',
  'Newark, DE',
  'Newark, NJ',
  'Nogales, AZ',
  'Norfolk, VA',
  'North Platte, NE',
  'Oakland, CA',
  'Ocala, FL',
  'Odessa, TX',
  'Ogden, UT',
  'Oklahoma City, OK',
  'Omaha, NE',
  'Ontario, CA',
  'Ontario, OR',
  'Orlando, FL',
  'Owensboro, KY',
  'Paducah, KY',
  'Parkersburg, WV',
  'Pasco, WA',
  'Paterson, NJ',
  'Pensacola, FL',
  'Peoria, IL',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'Pittsburgh, PA',
  'Plano, TX',
  'Pocatello, ID',
  'Portland, ME',
  'Portland, OR',
  'Providence, RI',
  'Provo, UT',
  'Pueblo, CO',
  'Racine, WI',
  'Raleigh, NC',
  'Rapid City, SD',
  'Reading, PA',
  'Redding, CA',
  'Reno, NV',
  'Richmond, VA',
  'Riverside, CA',
  'Roanoke, VA',
  'Rochester, MN',
  'Rochester, NY',
  'Rock Hill, SC',
  'Rock Springs, WY',
  'Rockford, IL',
  'Rocky Mount, NC',
  'Roswell, NM',
  'Sacramento, CA',
  'Saginaw, MI',
  'Salem, OR',
  'Salina, KS',
  'Salinas, CA',
  'Salisbury, MD',
  'Salt Lake City, UT',
  'San Angelo, TX',
  'San Antonio, TX',
  'San Bernardino, CA',
  'San Diego, CA',
  'San Francisco, CA',
  'San Jose, CA',
  'Santa Fe, NM',
  'Sarasota, FL',
  'Savannah, GA',
  'Scranton, PA',
  'Seattle, WA',
  'Secaucus, NJ',
  'Shreveport, LA',
  'Sikeston, MO',
  'Sioux City, IA',
  'Sioux Falls, SD',
  'South Bend, IN',
  'Sparks, NV',
  'Spartanburg, SC',
  'Spokane, WA',
  'Springfield, IL',
  'Springfield, MA',
  'Springfield, MO',
  'St. Cloud, MN',
  'St. George, UT',
  'St. Joseph, MO',
  'St. Louis, MO',
  'St. Paul, MN',
  'St. Petersburg, FL',
  'Stamford, CT',
  'Stockton, CA',
  'Syracuse, NY',
  'Tacoma, WA',
  'Tallahassee, FL',
  'Tampa, FL',
  'Tempe, AZ',
  'Terre Haute, IN',
  'Texarkana, AR',
  'Texarkana, TX',
  'Toledo, OH',
  'Topeka, KS',
  'Trenton, NJ',
  'Tucson, AZ',
  'Tulsa, OK',
  'Tupelo, MS',
  'Tuscaloosa, AL',
  'Twin Falls, ID',
  'Tyler, TX',
  'Utica, NY',
  'Valdosta, GA',
  'Vancouver, WA',
  'Victoria, TX',
  'Virginia Beach, VA',
  'Waco, TX',
  'Warwick, RI',
  'Waterbury, CT',
  'Waterloo, IA',
  'West Memphis, AR',
  'West Palm Beach, FL',
  'West Valley City, UT',
  'Wheeling, WV',
  'Wichita Falls, TX',
  'Wichita, KS',
  'Williston, ND',
  'Wilmington, DE',
  'Wilmington, NC',
  'Winchester, VA',
  'Winston-Salem, NC',
  'Worcester, MA',
  'Yakima, WA',
  'Yonkers, NY',
  'York, PA',
  'Youngstown, OH',
  'Yuma, AZ'
];
export default US_CITIES;
